# -*- coding: utf-8 -*-
"""Project@LAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vT9diNY7faWfT7xcR2kEtx3EP6vOMFAz
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
from tensorflow.keras.applications import ResNet50V2
from tensorflow.keras.models import load_model, Sequential
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam
import numpy as np
import os
from PIL import Image
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist

from google.colab import drive
drive.mount('/content/drive')

mm = load_model('/content/drive/MyDrive/ProjectML-@LAS/resnet50_similarity_model_full.h5')

BASE_DIR = '/content/drive/MyDrive/ProjectML-@LAS/ProjectML-@LAS/Google Images'

TRAIN_DIR = os.path.join(BASE_DIR, 'train')
VAL_DIR = os.path.join(BASE_DIR, 'val')
TEST_EVAL_DIR = os.path.join(BASE_DIR, 'test', 'test_')

IMAGE_SIZE = (224, 224)
BATCH_SIZE = 128
NUM_EPOCHS = 20
LEARNING_RATE = 0.0001

print(f"Directory สำหรับ Training: {TRAIN_DIR}")
print(f"Directory สำหรับ Testing/Evaluation: {TEST_EVAL_DIR}")

# @title 3.1 ข้ามไฟล์รูปที่เสียหาย
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

val_test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

validation_generator = val_test_datagen.flow_from_directory(
    VAL_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

test_generator = val_test_datagen.flow_from_directory(
    TEST_EVAL_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

NUM_CLASSES = train_generator.num_classes
print(f"จำนวนคลาสทั้งหมด: {NUM_CLASSES}")
print(f"ชื่อคลาส: {train_generator.class_indices}")

base_model = ResNet50V2(
    weights='imagenet',   # ใช้ Weights ที่เทรนแล้ว
    include_top=False,   # ไม่รวม Layer Output เดิม
    input_shape=(IMAGE_SIZE[0], IMAGE_SIZE[1], 3)
)

model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(NUM_CLASSES, activation='softmax') # 18 node outputs สำหรับ 18 คลาส
])

base_model = ResNet50V2(include_top=False, weights='imagenet', input_shape=(224,224,3))
x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dropout(0.5)(x)
outputs = tf.keras.layers.Dense(18, activation='softmax')(x)
model = tf.keras.Model(inputs=base_model.input, outputs=outputs)

model.save("model_retrieval.keras")

from tensorflow.keras.models import load_model

model = load_model('my_retrieval_model_final_atlas.h5', compile=False)
model.summary()

model.compile(
    optimizer=Adam(learning_rate=LEARNING_RATE),
    loss='categorical_csrossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // BATCH_SIZE,
    epochs=NUM_EPOCHS,
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // BATCH_SIZE
)

final_val_acc = history.history['val_accuracy'][-1]
print(f"\nValidation Accuracy สุดท้าย: {final_val_acc:.4f}")

test_generator.reset()

loss, accuracy = model.evaluate(test_generator,
                                steps=test_generator.samples // BATCH_SIZE + 1,
                                verbose=1)

print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

model.save('/content/drive/MyDrive/ProjectML-@LAS/resnet50_similarity_model_full.h5', include_optimizer=False)

predictions = model.predict(test_generator, steps=test_generator.samples // BATCH_SIZE + 1)
predicted_classes = tf.argmax(predictions, axis=1)

true_classes = test_generator.classes
label_map = {v: k for k, v in train_generator.class_indices.items()}

for i in range(10):
    predicted_label = label_map[predicted_classes.numpy()[i]]
    true_label = label_map[true_classes[i]]
    result = "ถูกต้อง" if predicted_classes.numpy()[i] == true_classes[i] else "ผิด"
    print(f"ไฟล์: {test_generator.filenames[i]} ------ predict: {predicted_label} ----|---- actual: {true_label} ({result})")

SINGLE_IMAGE_PATH = '/content/img.jpg'

import numpy as np
from tensorflow.keras.preprocessing import image
from PIL import Image

IMAGE_SIZE = (224, 224)
try:
    img = image.load_img(SINGLE_IMAGE_PATH, target_size=IMAGE_SIZE)
    img_array = image.img_to_array(img)

    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0

    predictions = model.predict(img_array)

    predicted_class_index = np.argmax(predictions[0])
    confidence = np.max(predictions[0])

    label_map = {v: k for k, v in train_generator.class_indices.items()}
    predicted_label = label_map[predicted_class_index]

    print(f"โมเดลทำนายว่าเป็นสถานที่: {predicted_label}")
    print(f"ด้วยความมั่นใจ: {confidence * 100:.2f}%")

except FileNotFoundError:
    print(f"ไม่พบไฟล์รูปภาพที่ Path: {SINGLE_IMAGE_PATH}")
except NameError:
    print("ตัวแปร 'model' หรือ 'train_generator' ไม่ถูกกำหนด กรุณารัน Cell 4 และ Cell 3 อีกครั้ง")
except Exception as e:
    print(f"เกิดข้อผิดพลาดในการประมวลผลรูปภาพ: {e}")

from tensorflow.keras.models import Sequential
import numpy as np

feature_extractor = Sequential(model.layers[:-2])
feature_extractor.build((None, IMAGE_SIZE[0], IMAGE_SIZE[1], 3))

import os
from tqdm.notebook import tqdm
import numpy as np

train_generator.reset()
all_features = []
all_paths = []

num_steps = train_generator.samples // BATCH_SIZE + 1

for i in tqdm(range(num_steps), desc="Building DB"):
    x, y = next(train_generator)
    features = feature_extractor.predict_on_batch(x)
    all_features.append(features)

    current_index = i * BATCH_SIZE
    current_paths = [os.path.join(train_generator.directory, path) for path in train_generator.filenames[current_index : current_index + len(x)]]
    all_paths.extend(current_paths)

all_features = np.concatenate(all_features)
print(f"\nฐานข้อมูล Feature: {all_features.shape[0]}")

np.save('/content/drive/MyDrive/ProjectML-@LAS/features.npy', all_features)
np.save('/content/drive/MyDrive/ProjectML-@LAS/paths.npy', all_paths)

from scipy.spatial.distance import cdist
from PIL import Image
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import os

def predict_and_find_similar(input_path, num_results=5):

    img = image.load_img(input_path, target_size=IMAGE_SIZE)
    img_prepped = np.expand_dims(image.img_to_array(img), axis=0) / 255.0

    # 1. ทำนายคลาส
    predictions_proba = model.predict(img_prepped, verbose=0)
    predicted_class_index = np.argmax(predictions_proba[0])
    label_map = {v: k for k, v in train_generator.class_indices.items()}
    predicted_label = label_map[predicted_class_index]
    confidence = np.max(predictions_proba[0])
    print(f"Predict: {predicted_label} Confidence: {confidence * 100:.2f}%")

    # 2. กรองฐานข้อมูล Features
    all_classes_from_path = [os.path.basename(os.path.dirname(p)) for p in all_paths]
    filtered_indices = [i for i, c in enumerate(all_classes_from_path) if c == predicted_label]
    filtered_features = all_features[filtered_indices]
    filtered_paths = [all_paths[i] for i in filtered_indices]

    # 3. ค้นหาความคล้ายคลึง
    input_feature = feature_extractor.predict_on_batch(img_prepped)
    distances = cdist(input_feature, filtered_features, metric='euclidean')[0] # <--- เปลี่ยนเป็น Euclidean

    similar_indices = np.argsort(distances)[:num_results]
    final_results = [(filtered_paths[i], distances[i]) for i in similar_indices]


    num_columns = num_results + 1 # 1 Query + 5 Results = 6 ช่อง

    plt.figure(figsize=(18, 6))

    # แสดงรูป Query (ช่องที่ 1)
    plt.subplot(1, num_columns, 1)
    plt.imshow(img)
    plt.title(f"1. Query (TEST)\n{predicted_label}")
    plt.axis('off')

    # แสดงผลการค้นหา 5 อันดับแรก (ช่องที่ 2 - 6)
    for i, (path, dist) in enumerate(final_results):
        plt.subplot(1, num_columns, i + 2) # เริ่มจากตำแหน่งที่ 2
        sim_img = Image.open(path)

        source_folder = "TRAIN/VAL"
        if "test" in path.lower():
             source_folder = "TEST"

        plt.imshow(sim_img)
        plt.title(f"Rank {i+1} ({source_folder})\nDist: {dist:.4f}")
        plt.axis('off')

    plt.tight_layout()
    plt.show()

import json

class_indices = train_generator.class_indices
with open("class_indices.json", "w") as f:
    json.dump(class_indices, f)

# @title 8.1 ทดสอบจาก test
INDEX_TO_TEST = 9
test_generator.reset()
try:
    file_name_to_test = test_generator.filenames[INDEX_TO_TEST]
    test_sample_path = os.path.join(TEST_EVAL_DIR, file_name_to_test)
    predict_and_find_similar(test_sample_path, num_results=5)
except Exception as e:
    print(f"{e}")

MY_UPLOADED_IMAGE_PATH = '/content/img.jpg'

# @title 8.2 ทดสอบจากรูป upload
if os.path.exists(MY_UPLOADED_IMAGE_PATH):
    predict_and_find_similar(MY_UPLOADED_IMAGE_PATH, num_results=5)
else:
    print(f"\nไม่พบไฟล์ {MY_UPLOADED_IMAGE_PATH}")

import os

SAVE_DIR = '/content/drive/MyDrive/ProjectML-@LAS/ProjectML-@LAS/Google Images'
MODEL_FILENAME = 'my_retrieval_model_final_atlas.h5'
FULL_SAVE_PATH = os.path.join(SAVE_DIR, MODEL_FILENAME)

model.save(FULL_SAVE_PATH)

print(f"บันทึกโมเดลสำเร็จที่: {FULL_SAVE_PATH}")

import numpy as np
import os
SAVE_DIR = '/content/drive/MyDrive/ProjectML-@LAS/'
np.save(os.path.join(SAVE_DIR, 'all_features.npy'), all_features)

import numpy as np
import os
SAVE_DIR = '/content/drive/MyDrive/ProjectML-@LAS/'
np.save(os.path.join(SAVE_DIR, 'all_paths.npy'), all_paths, allow_pickle=True)

MODEL_SAVE_PATH = '/content/drive/MyDrive/ProjectML-@LAS/my_retrieval_model_final_atlas.keras'
model.save(MODEL_SAVE_PATH)
print(f"บันทึกโมเดลใหม่สำเร็จที่: {MODEL_SAVE_PATH}")

base_model_to_save = model.layers[0]

WEIGHTS_SAVE_PATH = '/content/drive/MyDrive/ProjectML-@LAS/resnet_weights.weights.h5'
base_model_to_save.save_weights(WEIGHTS_SAVE_PATH)

print(f"บันทึกไฟล์น้ำหนักสำเร็จที่: {WEIGHTS_SAVE_PATH}")

import numpy as np

raw_weights = model.layers[0].get_weights()

WEIGHTS_SAVE_PATH = '/content/drive/MyDrive/ProjectML-@LAS/resnet_raw_weights_fixed.npy' # เปลี่ยนชื่อไฟล์

np.save(WEIGHTS_SAVE_PATH, np.array(raw_weights, dtype=object), allow_pickle=True)

print(f"บันทึกไฟล์น้ำหนักดิบสำเร็จที่: {WEIGHTS_SAVE_PATH}")

import json

class_indices = train_generator.class_indices
with open('class_indices.json', 'w') as f:
    json.dump(class_indices, f)
print("บันทึก class_indices.json เรียบร้อย")

import numpy as np
import json
import os
# ตัวแปรเหล่านี้ควรจะพร้อมใช้งานแล้ว: model, train_generator, all_features, all_paths

# 1. บันทึก Model
model.save('my_model.h5')
print("✅ 1. บันทึก my_model.h5 เรียบร้อย")

# 2. บันทึก Label Map (จำเป็นสำหรับ Streamlit)
class_indices = train_generator.class_indices
# บันทึกเป็น Class Name (string) : Index (int)
with open('class_indices.json', 'w') as f:
    json.dump(class_indices, f)
print("✅ 2. บันทึก class_indices.json เรียบร้อย")

# 3. บันทึกฐานข้อมูล Features
np.save('all_features.npy', all_features)
print(f"✅ 3. บันทึก all_features.npy เรียบร้อย ({all_features.shape})")

# 4. บันทึก Paths พร้อมแก้ไขให้เป็น Placeholder (สำคัญมาก!)
# BASE_DIR ในโค้ดคุณคือ: /content/drive/MyDrive/ProjectML-@LAS/Google Images
# เราจะแทนที่ส่วนของ Google Drive ด้วย PLACEHOLDER_PREFIX/

# ใช้ BASE_DIR ที่คุณกำหนดไว้ในโค้ดต้นฉบับ
# ตัวอย่างเช่น /content/drive/MyDrive/ProjectML-@LAS
drive_path_prefix_to_remove = os.path.dirname(BASE_DIR)

paths_for_app = []

for p in all_paths:
    # เปลี่ยน Path ใน Drive เป็น Placeholder
    # เช่น /content/drive/MyDrive/ProjectML-@LAS/Google Images/train/ClassX/img.jpg
    # จะกลายเป็น PLACEHOLDER_PREFIX/Google Images/train/ClassX/img.jpg
    p_relative = p.replace(drive_path_prefix_to_remove, 'PLACEHOLDER_PREFIX')
    paths_for_app.append(p_relative)

with open('all_paths.txt', 'w') as f:
    for item in paths_for_app:
        f.write("%s\n" % item)

print("✅ 4. บันทึก all_paths.txt เรียบร้อย (ใช้ Placeholder)")

# โค้ดสำหรับบันทึกโมเดลใหม่ใน Colab
# ------------------------------------
# 1. บังคับให้ใช้ Keras API โดยตรง
import keras
from tensorflow.keras.models import load_model

# 2. บันทึกโมเดลด้วย save_format='h5'
# นี่เป็นวิธีที่เข้ากันได้ง่ายที่สุด
# โดยให้ชื่อไฟล์ใหม่เป็น 'my_model_v2.h5'
model.save('my_model_v2.h5', save_format='h5')

print("บันทึกโมเดลใหม่สำเร็จในชื่อ my_model_v2.h5")

# รันโค้ดบันทึกไฟล์ .npy และ .json อื่นๆ ด้วย
# ... (โค้ดบันทึก all_features.npy, all_paths.txt, class_indices.json)
# ------------------------------------

# โค้ดสำหรับบันทึกโมเดลใน Colab (สำหรับ Keras 3 โดยเฉพาะ)
# ----------------------------------------------------------------------
import tensorflow as tf
import keras
import os
import shutil # สำหรับลบโฟลเดอร์ชั่วคราว

# 1. กำหนดชื่อไฟล์ใหม่ (ใช้ .keras นามสกุลใหม่ที่ดีที่สุด)
# นี่คือรูปแบบที่ Keras 3 แนะนำและยืดหยุ่นกว่า .h5
final_keras_path = 'final_working_model.keras'

# 2. บันทึกโมเดลโดยตรง (Keras 3 จะใช้รูปแบบ .keras อัตโนมัติ)
# ถ้าโมเดลเคยถูกบันทึกมาแล้ว ควรลบออกก่อน
if os.path.exists(final_keras_path):
    os.remove(final_keras_path)

model.save(final_keras_path)

print(f"บันทึกโมเดลที่เข้ากันได้สำเร็จในชื่อ: {final_keras_path}")

# 3. ลบโฟลเดอร์ชั่วคราว (ถ้ามี)
if os.path.isdir('temp_model_tf'):
    shutil.rmtree('temp_model_tf')

# 4. รันโค้ดบันทึกไฟล์ .npy และ .json อื่นๆ ด้วย
# ... (คุณต้องมั่นใจว่าโค้ดบันทึก all_features.npy, all_paths.txt, class_indices.json อยู่ใน Cell นี้หรือรันไปแล้ว)
# ----------------------------------------------------------------------

# เพิ่มโค้ดนี้ใน Colab ต่อจากเซลล์ที่เทรนเสร็จแล้ว

# 1. บันทึกโมเดลหลัก
model.save('my_image_classifier_model.h5') # หรือ .keras
print("บันทึกโมเดลหลักแล้ว")

# 2. บันทึกตัวสกัดคุณลักษณะ (Feature Extractor)
feature_extractor.save('my_feature_extractor_model.h5')
print("บันทึก Feature Extractor แล้ว")

# 3. บันทึกฐานข้อมูล Features และ Paths
import numpy as np
import pickle

np.save('all_features.npy', all_features)
with open('all_paths.pkl', 'wb') as f:
    pickle.dump(all_paths, f)
print("บันทึกฐานข้อมูล Features และ Paths แล้ว")

# 4. บันทึก Label Map
import json
with open('class_indices.json', 'w') as f:
    json.dump(train_generator.class_indices, f)
print("บันทึก Class Indices แล้ว")

from tensorflow.keras.models import load_model

SAVE_DIR = '/content/drive/MyDrive/ProjectML-@LAS/ProjectML-@LAS'
MODEL_FILENAME = 'my_retrieval_model_final_atlas.h5'
FULL_SAVE_PATH = os.path.join(SAVE_DIR, MODEL_FILENAME)

model = load_model(FULL_SAVE_PATH)
print("โหลดโมเดลสำเร็จ ✅")

SAVE_DIR = '/content/drive/MyDrive/ProjectML-@LAS/ProjectML-@LAS'
MODEL_PATH = os.path.join(SAVE_DIR, 'my_retrieval_model_final_atlas.h5')

model = load_model(MODEL_PATH)
model.summary()
# all_features = np.load(os.path.join(SAVE_DIR, 'all_features.npy'))
# all_paths = np.load(os.path.join(SAVE_DIR, 'all_paths.npy'), allow_pickle=True)

# print(f"all_features shape: {all_features.shape}")
# print(f"จำนวน path: {len(all_paths)}")

IMAGE_SIZE = (224, 224)
feature_extractor = Sequential(model.layers[:-2])
feature_extractor.build((None, IMAGE_SIZE[0], IMAGE_SIZE[1], 3))

def predict_and_find_similar(input_path, num_results=5):
    # เตรียมภาพ input
    img = image.load_img(input_path, target_size=IMAGE_SIZE)
    img_prepped = np.expand_dims(image.img_to_array(img), axis=0) / 255.0

    # 1. ทำนายคลาส
    predictions_proba = model.predict(img_prepped, verbose=0)
    predicted_class_index = np.argmax(predictions_proba[0])
    confidence = np.max(predictions_proba[0])
    print(f"Predict class index: {predicted_class_index}, Confidence: {confidence * 100:.2f}%")

    # 2. คำนวณ feature ของภาพ input
    input_feature = feature_extractor.predict_on_batch(img_prepped)

    # 3. คำนวณระยะทาง Euclidean กับฐานข้อมูลทั้งหมด
    distances = cdist(input_feature, all_features, metric='euclidean')[0]
    similar_indices = np.argsort(distances)[:num_results]

    # 4. แสดงภาพผลลัพธ์
    plt.figure(figsize=(18, 6))
    plt.subplot(1, num_results + 1, 1)
    plt.imshow(img)
    plt.title("Query Image")
    plt.axis('off')

    for i, idx in enumerate(similar_indices):
        sim_img = Image.open(all_paths[idx])
        plt.subplot(1, num_results + 1, i + 2)
        plt.imshow(sim_img)
        plt.title(f"Rank {i+1}\nDist: {distances[idx]:.4f}")
        plt.axis('off')

    plt.tight_layout()
    plt.show()

import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from tensorflow.keras.preprocessing import image
from scipy.spatial.distance import cdist

def predict_and_find_similar(input_path, num_results=5):
    # --- ตรวจสอบไฟล์ input ---
    if not os.path.exists(input_path):
        print(f"❌ ไม่พบไฟล์รูปภาพ: {input_path}")
        return

    # --- เตรียมภาพ input ---
    img = image.load_img(input_path, target_size=IMAGE_SIZE)
    img_prepped = np.expand_dims(image.img_to_array(img), axis=0) / 255.0

    # --- 1. ทำนายคลาส ---
    predictions_proba = model.predict(img_prepped, verbose=0)
    predicted_class_index = np.argmax(predictions_proba[0])
    confidence = np.max(predictions_proba[0])
    print(f"✅ Predict class index: {predicted_class_index}, Confidence: {confidence * 100:.2f}%")

    # --- 2. คำนวณ feature ของภาพ input ---
    input_feature = feature_extractor.predict_on_batch(img_prepped)

    # --- 3. คำนวณระยะทาง Euclidean กับฐานข้อมูลทั้งหมด ---
    distances = cdist(input_feature, all_features, metric='euclidean')[0]
    similar_indices = np.argsort(distances)[:num_results]

    # --- 4. แสดงภาพผลลัพธ์ ---
    plt.figure(figsize=(18, 6))
    plt.subplot(1, num_results + 1, 1)
    plt.imshow(img)
    plt.title("Query Image")
    plt.axis('off')

    shown = 0
    for idx in similar_indices:
        path = str(all_paths[idx])  # แปลงให้เป็น string ปกติ
        if not os.path.exists(path):
            print(f"⚠️ ไม่พบไฟล์: {path}")
            continue

        try:
            sim_img = Image.open(path)
        except Exception as e:
            print(f"⚠️ เปิดไฟล์ไม่ได้: {path} ({e})")
            continue

        shown += 1
        plt.subplot(1, num_results + 1, shown + 1)
        plt.imshow(sim_img)
        plt.title(f"Rank {shown}\nDist: {distances[idx]:.4f}")
        plt.axis('off')

        if shown >= num_results:
            break

    if shown == 0:
        print("❌ ไม่มีไฟล์ที่สามารถแสดงได้เลย")
    else:
        plt.tight_layout()
        plt.show()

"""### ***The Last Of Process Project***"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import load_model, Model
from tensorflow.keras.applications.resnet_v2 import preprocess_input
from tensorflow.keras.utils import load_img, img_to_array
import numpy as np
import os
from PIL import Image, ImageFile
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist
from google.colab import drive
from tqdm import tqdm

drive.mount('/content/drive', force_remount=True)

SAVE_DIR = '/content/drive/MyDrive/ProjectML-@LAS/ProjectML-@LAS/'
MODEL_PATH = os.path.join(SAVE_DIR, 'my_retrieval_model_final_atlas.h5')
BASE_DIR = os.path.join(SAVE_DIR, 'Google Images')

TRAIN_DIR = os.path.join(BASE_DIR, 'train')
VAL_DIR = os.path.join(BASE_DIR, 'val')
TEST_DIR = os.path.join(BASE_DIR, 'test', 'test_')

IMAGE_SIZE = (224, 224)
BATCH_SIZE = 128
ImageFile.LOAD_TRUNCATED_IMAGES = True

model = load_model(MODEL_PATH, compile=False)

target_layer_name = None
for layer in model.layers:
    if "global_average_pooling" in layer.name:
        target_layer_name = layer.name
        break

if target_layer_name is None:
    raise ValueError("❌ ไม่พบเลเยอร์ global_average_pooling ในโมเดล")

inp = tf.keras.layers.Input(shape=(IMAGE_SIZE[0], IMAGE_SIZE[1], 3))
x = inp
for layer in model.layers:
    x = layer(x)
    if layer.name == target_layer_name:
        break
feature_extractor = Model(inputs=inp, outputs=x)
print("✅ Feature extractor ready! Output shape:", feature_extractor.output_shape)

train_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(
    TRAIN_DIR, target_size=IMAGE_SIZE, batch_size=BATCH_SIZE, class_mode='categorical'
)
label_map = {v: k for k, v in train_generator.class_indices.items()}

def build_feature_database(base_dirs, output_dir):
    all_features, all_paths = [], []

    for base_dir in base_dirs:
        print(f"\n📂 Processing folder: {base_dir}")
        for root, _, files in os.walk(base_dir):
            for file in tqdm(files, desc=os.path.basename(root)):
                if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                    img_path = os.path.join(root, file)
                    try:
                        img = load_img(img_path, target_size=IMAGE_SIZE)
                        img_array = np.expand_dims(img_to_array(img), axis=0)
                        img_array = preprocess_input(img_array)
                        feature = feature_extractor.predict(img_array, verbose=0)
                        all_features.append(feature.flatten())
                        all_paths.append(img_path)
                    except Exception as e:
                        print(f"⚠️ Skip: {img_path} ({e})")

    np.save(os.path.join(output_dir, 'all_features.npy'), np.array(all_features))
    np.save(os.path.join(output_dir, 'all_paths.npy'), np.array(all_paths))
    print("\n✅ Features database rebuilt successfully!")
    print(f"Total: {len(all_paths)} images | Shape: {np.array(all_features).shape}")

# 🧩 ถ้าต้องการสร้างใหม่ ให้ uncomment
build_feature_database([TRAIN_DIR, VAL_DIR, TEST_DIR], SAVE_DIR)

all_features = np.load(os.path.join(SAVE_DIR, 'all_features.npy'))
all_paths = np.load(os.path.join(SAVE_DIR, 'all_paths.npy'), allow_pickle=True)
print("📦 Loaded feature DB:", all_features.shape)

def predict_and_find_similar(input_path, num_results=5, batch_size=128):
    img = load_img(input_path, target_size=IMAGE_SIZE)
    img_prepped = np.expand_dims(img_to_array(img), axis=0)
    img_prepped = preprocess_input(img_prepped)

    predictions_proba = model.predict(img_prepped, verbose=0)
    predicted_class_index = np.argmax(predictions_proba[0])
    predicted_label = label_map[predicted_class_index]
    confidence = np.max(predictions_proba[0])
    print(f"🔍 Predict: {predicted_label} | Confidence: {confidence * 100:.2f}%")

    all_classes_from_path = [os.path.basename(os.path.dirname(p)) for p in all_paths]
    filtered_indices = [i for i, c in enumerate(all_classes_from_path) if c == predicted_label]
    filtered_features = all_features[filtered_indices]
    filtered_paths = [str(all_paths[i]) for i in filtered_indices]

    query_feature_full = feature_extractor.predict(img_prepped, verbose=0).flatten()

    input_feature = query_feature_full[:filtered_features.shape[1]]

    distances = []
    num_batches = int(np.ceil(len(filtered_features) / batch_size))
    for i in tqdm(range(num_batches), desc="Distances (batches)"):
        start = i * batch_size
        end = min((i + 1) * batch_size, len(filtered_features))
        batch_features = filtered_features[start:end]
        batch_dist = np.linalg.norm(batch_features - input_feature, axis=1)
        distances.extend(batch_dist)
    distances = np.array(distances)

    similar_indices = np.argsort(distances)[:num_results]
    final_results = [(filtered_paths[i], distances[i]) for i in similar_indices]

    num_columns = num_results + 1
    plt.figure(figsize=(18, 6))

    plt.subplot(1, num_columns, 1)
    plt.imshow(img)
    plt.title(f"Query\n({predicted_label})")
    plt.axis('off')

    for i, (path, dist) in enumerate(final_results):
        plt.subplot(1, num_columns, i + 2)
        sim_img = Image.open(path)
        plt.imshow(sim_img)
        plt.title(f"Rank {i+1}\nDist: {dist:.4f}")
        plt.axis('off')

    plt.tight_layout()
    plt.show()


MY_QUERY_IMAGE = '/content/drive/MyDrive/ProjectML-@LAS/ProjectML-@LAS/Google Images/test/test_/Pyramids Of Giza - Egypt/180.jpg'
# MY_QUERY_IMAGE = '/content/bg-mobile.jpg'
# MY_QUERY_IMAGE = '/content/kmutnb.png'

if os.path.exists(MY_QUERY_IMAGE):
    predict_and_find_similar(MY_QUERY_IMAGE, num_results=5, batch_size=128)
else:
    print(f"❌ ไม่พบไฟล์: {MY_QUERY_IMAGE}")